@startuml StringCalculator
class StringCalculator {
	- CALCURATOR_STRING_PATTERN : String
	- stringParsor : StringCalculatorParsor

	+ calcuration(calcuratingString: String) : Integer
	- isInvalidValue(calcuratingString: String) : Boolean
}

class StringCalculatorParsor {
	+ CUSTOM_SEPARATOR_PARSING_PATTERN : string
	- separators : Separators

	- setDefaultSeparator() : void
	+ parse(calcuratingString: String) : CalculatorNumbers
}

class CalculatorNumbers {
	- items : List<CalculatorNumber>

	+ sum() : Integer
}

class CalculatorNumber {
	- item : Integer

	- isInvalid(number: String) : Boolean
}

class Separators {
	- items : List<Separators>

	+ getSeparators() : String
	+ add(separator: Separator) : Boolean
}

class Separator {
	- item : String
}

StringCalculator <-- StringCalculatorParsor

StringCalculatorParsor <-- CalculatorNumbers
StringCalculatorParsor  <--  Separators

CalculatorNumbers "1" *-- "0..*" CalculatorNumber

Separators "1" *-- "1..*" Separator
@enduml